#! /bin/sh
### BEGIN INIT INFO
# chkconfig: 2345 24 76
# description: XenServer btier tiered storage
# config: /etc/bttab
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin
TS=/sbin/btier_setup

. /lib/lsb/init-functions

if [ ! -d /sys/class/ ]; then
  log_failure_msg "btier requires a mounted sysfs, not started."
  exit 0
fi

RETVAL=0

sanitychecks() {
        # Do sanity checks before we start.
        mod=/lib/modules/`uname -r`/kernel/drivers/block/btier.ko
        if [ ! -f $mod ]; then 
            log_failure_msg "btier kernel module not found."
            exit 1
        fi
}

start() {
        log_action_msg "Loading the btier device"
        sanitychecks
        modprobe -q btier 2>/dev/null || :
        for t in `cat /etc/bttab | grep -v "^#"`
        do
           $TS -f $t  
           if [ $? != 0 ]
              then
                echo "Failed to setup tier device : $TS -f $t"
                exit 1
           fi
        done
	log_end_msg 0
}

stop() {
	log_action_msg "Unloading the btier devices"
        for t in `ls /dev/sdtier* | sort -r`
        do
           $TS -d $t
           if [ $? != 0 ]
              then
                echo "Failed to deregister tier device : $TS -d $t"
                exit 1
           fi
        done
	modprobe -r btier 2>/dev/null
	log_end_msg 0
}

restart() {
	stop
	start
        exit 0
}

status() {
	# list active sessions
        if [ ! -e /dev/tiercontrol ]
           then 
	   log_action_msg "btier.ko module is not registered" 
           exit 1
        fi
	log_action_msg /dev/sdtier*
	exit 0
}

if [ -z "${MODE}" ]
then
        MODE=$1
fi

case "$MODE" in
	start|stop|restart|status)
		$MODE
		;;
	force-reload)
		restart
		;;
	*)
		log_success_msg "Usage: $0 {start|stop|restart|status}"
		exit 1
		;;
esac
exit $RETVAL
