#! /bin/sh -x
### BEGIN INIT INFO
# chkconfig: 2345 99 01
# description: XenServer btier tiered storage
# config: /etc/bttab
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin
TS=/sbin/btier_setup

. /lib/lsb/init-functions

if [ ! -d /sys/class/ ]; then
  logger -p warn "btier requires a mounted sysfs, not started."
  exit 0
fi

RETVAL=0

sanitychecks() {
        # Do sanity checks before we start.
        mod=/lib/modules/`uname -r`/kernel/drivers/block/btier.ko
        if [ ! -f $mod ]; then 
            logger -p warn "btier kernel module not found."
            exit 1
        fi
}

start() {
        # Need this to be present so that we get run on shutdown.
        touch /var/lock/subsys/btier
        ec=0
        logger -p info "Loading the btier device"
        sanitychecks
        modprobe -q btier 2>/dev/null || :
        for t in `cat /etc/bttab | grep -v "^#"`
        do
           for n in `echo $t | sed "s/:/ /g"`
           do
              while true
              do
                 lvchange -ay $n
                 if [ $? = 0 ]; then break; fi
                 sleep 1
                 $((ec+1))
                 if [ ${ec} -gt 60 ]; then break; fi
              done
           done
           $TS -f $t  
           if [ $? != 0 ]
              then
                echo "Failed to setup tier device : $TS -f $t"
                exit 1
           fi
        done
        sleep 1
        for t in `ls /dev/sdtier* | sort -r`
        do
           dev=$(echo $t | cut -d/ -f3)
           echo 0 >/sys/block/$dev/tier/sequential_landing
        done
	logger -p info 0
}

stop() {
	logger -p info "Unloading the btier devices"
        echo "Unloading the btier devices"
        for t in `ls /dev/sdtier* | sort -r`
        do
           $TS -d $t
           if [ $? != 0 ]
              then
                logger -p info "Failed to deregister tier device : $TS -d $t"
                echo "Failed to deregister tier device : $TS -d $t"
                exit 1
           fi
        done
	modprobe -r btier 2>/dev/null
        for t in `cat /etc/bttab | grep -v "^#"`
        do
           for n in `echo $t | sed "s/:/ /g"`
           do
              lvchange -an $n
           done
        done
        [ -f /var/lock/subsys/btier ] && rm -f /var/lock/subsys/btier
	logger -p info 0
}

restart() {
	stop
	start
        exit 0
}

status() {
	# list active sessions
        if [ ! -e /dev/tiercontrol ]
           then 
	      logger -p info "btier.ko module is not registered" 
           exit 1
        fi
	logger -p logger -p info /dev/sdtier*
        ls /dev/sdtier*
	exit 0
}

if [ -z "${MODE}" ]
then
        MODE=$1
fi

case "$MODE" in
	start|stop|restart|status)
		$MODE
		;;
	force-reload)
		restart
		;;
	*)
		log_success_msg "Usage: $0 {start|stop|restart|status}"
		exit 1
		;;
esac
exit $RETVAL
