obj-m += btier.o
btier-objs :=
btier-objs += btier_common.o
btier-objs += btier_sysfs.o
btier-objs += btier_main.o 
btier-objs += btier_request.o 

default:
	cd ../../; make 
clean:
	cd ../../; make clean
install:
	cd ../../; make install
uninstall:
	cd ../../; make uninstall
